# Dockerfile para el Pipeline ETL
# A diferencia de la API o el Dashboard, este contenedor no es un servidor 24/7.
# Es un contenedor "efímero" que se levantará, ejecutará el script ETL procesando 
# las 3 fuentes (CSV, API y Supabase), guardará los resultados y luego finalizará.
FROM python:3.11-slim

WORKDIR /app

# Optimizamos la instalación de librerías aprovechando la caché.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Necesitamos la carpeta etl con los scripts (.py) y data para depositar/leer los csv.
COPY ./etl ./etl
COPY ./data ./data

# Ejecutamos el orquestador principal que consolida el flujo de datos.
CMD ["python", "etl/main_etl.py"]
