FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./api ./api
COPY ./data ./data
COPY ./dashboards ./dashboards

EXPOSE 8050

CMD ["python", "dashboards/app.py"]
